language: java
jdk: oraclejdk8
sudo: required

before_install:
  - chmod +x gradlew

env:
  - ACTIVITY_TRACKER_IDEA_VERSION=IC-173.0

deploy:
  provider: releases
  api_key:
    secure: 2d185c3fe8385dec3dceffb21a53081607710dc4
  file: build/libs/TestHalloWorld-1.0.jar
  skip_cleanup: true